---
language: csharp

os:
  - linux
  - osx

mono:
  - 5.4.0
  - 5.4.1
  - latest
  - weekly

dist: trusty

dotnet: 2.0.3

install:
 - rvm install 2.2.3
 - gem install bundler
 - if [ "$TRAVIS_OS_NAME" == "linux" ];
   then sudo apt-get update -y;
   else brew update;
   fi

before_script:
 - if [ "$TRAVIS_OS_NAME" == "linux" ];
   then export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/.nuget/packages/libuv/1.10.0/runtimes/linux-x64/native;
   else ln -s ~/.nuget/packages/libuv/1.10.0/runtimes/osx/native/libuv.dylib /usr/local/lib/libuv.dylib;
   fi

script:
 - bundle && bundle exec rake ci

matrix:
  allow_failures:
    - mono: latest
    - mono: weekly
