---
language: csharp

os:
  - linux
  - osx

dist: trusty
sudo: required

dotnet: 1.0.4

mono:
 - 4.8.0
 - 5.2.0
 - latest # => "stable release"
 - weekly # => "latest commits"

install:
 - rvm install 2.2.3
 - gem install bundler
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -y ; else brew update ; fi 
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y gnupg automake libtool ; fi
 - curl -sSL https://github.com/libuv/libuv/archive/v1.9.1.tar.gz | tar zxf - -C /tmp
 - (cd /tmp/libuv-1.9.1/ && ./autogen.sh && ./configure && make && sudo make install)
 - sudo ldconfig
 # for apache bench (ab)
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; sudo apt-get install -qq apache2-utils ; fi

script:
 - bundle && bundle exec rake ci

matrix:
  allow_failures:
    - mono: latest
    - mono: weekly
    - mono: 5.0.0
