---
language: csharp

#dist: trusty
#sudo: required

dotnet: 2.0.3

mono:
 - 5.4.0
 - 5.4.1
 - latest # => "stable release"
 - weekly # => "latest commits"

install:
 - rvm install 2.2.3
 - gem install bundler
 - sudo apt-get update -y

 #- sudo apt-get install -y gnupg automake libtool
 #- curl -sSL https://github.com/libuv/libuv/archive/v1.9.1.tar.gz | tar zxf - -C /tmp
 #- (cd /tmp/libuv-1.9.1/ && ./autogen.sh && ./configure && make && sudo make install)
 #- sudo ldconfig
 # for apache bench (ab)
 # - sudo apt-get install -qq apache2-utils


before_script:
 - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/travis/.nuget/packages/libuv/1.10.0/runtimes/linux-x64/native

script:
 - bundle && bundle exec rake ci

matrix:
  allow_failures:
    - mono: latest
    - mono: weekly
    - mono: 5.0.0
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
    - os: osx # OSX 10.12
      osx_image: xcode9.1
      dist: trusty
      #sudo: required